apiVersion: v1
kind: ConfigMap
metadata:
  name: grafain-genesis
data:
  genesis.json: |-
    {
      "chain_id": "grafain-demo",
      "genesis_time": "2019-10-01T08:00:00Z",
      "consensus_params": {
        "block": {
          "max_bytes": "500000",
          "max_gas": "-1",
          "time_iota_ms": "1000"
        },
        "evidence": {
          "max_age": "100000"
        },
        "validator": {
          "pub_key_types": [
            "ed25519"
          ]
        }
      },
      "validators": [],
      "app_hash": "",
      "app_state": {
        "artifacts": [
          {
          "image":    "alpetest/grafain:manual",
          "owner":    "0E95C039EF14EE329D0E09D84F909CF9EB5EF472",
          "checksum": "anyValidChecksum"
          },
          {
           "image":    "alpetest/grafain:latest",
           "owner":    "0E95C039EF14EE329D0E09D84F909CF9EB5EF472",
           "checksum": "anyValidChecksum"
          }
        ],
        "cash": [
        {
          "address": "0E95C039EF14EE329D0E09D84F909CF9EB5EF472",
          "//name": "faucet",
          "coins": [
          {
            "whole": 999999999,
            "ticker": "GRFN"
          }
          ]
        }
        ],
        "currencies": [
        {
          "ticker": "GRFN",
          "name": "Unused Grafain utility token"
        }
        ],
        "multisig": [
        {
          "activation_threshold": 3,
          "admin_threshold": 3,
          "//name": "admin multisig",
          "participants": [
          {
            "signature": "0E95C039EF14EE329D0E09D84F909CF9EB5EF472",
            "weight": 3
          }
          ]
        }
        ],
        "rbac": {
          "roles": [
            {
              "name": "system.admin",
              "owner": "seq:rbac/role/1",
              "permissions": [
                "_grafain.*"
              ]
            },
            {
              "name": "k8s.admin",
              "owner": "seq:rbac/role/1",
              "permissions": [
                "_grafain.artifact.delete"
              ]
            },
            {
              "name": "k8s.devops",
              "owner": "seq:rbac/role/1",
              "role_ids": [ 2 ],
              "permissions": [
                "_grafain.artifacts.create"
              ]
            }
          ],
          "principals": [
            {
              "name": "Alice",
              "signatures": [
                {
                  "name": "admin",
                  "signature": "cond:multisig/usage/0000000000000001"
                },
                {
                  "name": "devops",
                  "signature": "0E95C039EF14EE329D0E09D84F909CF9EB5EF472"
                }
              ]
            }
          ],
          "role_bindings": [
            {
              "role_id": 1,
              "signature": "cond:multisig/usage/0000000000000001"
            },
            {
              "role_id": 3,
              "signature": "0E95C039EF14EE329D0E09D84F909CF9EB5EF472"
            }
          ]
        },
        "update_validators": {
          "addresses": [
            "cond:multisig/usage/0000000000000001"
          ]
        },
        "conf": {
          "cash": {
            "owner": "cond:multisig/usage/0000000000000001",
            "collector_address": "cond:multisig/usage/0000000000000001",
            "minimal_fee": "0.0 GRFN"
          },
          "migration": {
            "admin": "cond:multisig/usage/0000000000000001",
            "//admin": "owned by admin multisig"
          },
          "msgfee": {
            "owner": "cond:multisig/usage/0000000000000001",
            "fee_admin": "cond:multisig/usage/0000000000000001"
          }
        },
        "msgfee": [],
        "governance": {},
        "initialize_schema": [
        {
          "pkg": "artifact",
          "ver": 1
        },
        {
          "pkg": "aswap",
          "ver": 1
        },
        {
          "pkg": "batch",
          "ver": 1
        },
        {
          "pkg": "cash",
          "ver": 1
        },
        {
          "pkg": "cron",
          "ver": 1
        },
        {
          "pkg": "currency",
          "ver": 1
        },
        {
          "pkg": "distribution",
          "ver": 1
        },
        {
          "pkg": "escrow",
          "ver": 1
        },
        {
          "pkg": "gov",
          "ver": 1
        },
        {
          "pkg": "hashlock",
          "ver": 1
        },
        {
          "pkg": "msgfee",
          "ver": 1
        },
        {
          "pkg": "multisig",
          "ver": 1
        },
        {
          "pkg": "namecoin",
          "ver": 1
        },
        {
          "pkg": "username",
          "ver": 1
        },
        {
          "pkg": "paychan",
          "ver": 1
        },
        {
          "pkg": "rbac",
          "ver": 1
        },
        {
          "pkg": "sigs",
          "ver": 1
        },
        {
          "pkg": "utils",
          "ver": 1
        },
        {
          "pkg": "validators",
          "ver": 1
        }
        ]
      }
    }
