apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: grafain
webhooks:
- name: grafain.default.svc
  failurePolicy: Ignore
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      operations:
        - CREATE
      resources:
        - pods
      scope: "Namespaced"
  clientConfig:
    service:
      namespace: default
      name: grafain
      path: /
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHRENDQWdDZ0F3SUJBZ0lVQzN1aVliYzFqVFFxSzlCaGdCMHJZOEhtRVBJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pERVFNQTRHQTFVRUNoTUhSM0poWm1GcGJqRVFNQTRHQTFVRUF4TUhaM0poWm1GcGJqQWVGdzB4T1RBNQpNVEF4T1RBM01EQmFGdzB5TkRBNU1EZ3hPVEEzTURCYU1DUXhFREFPQmdOVkJBb1RCMGR5WVdaaGFXNHhFREFPCkJnTlZCQU1UQjJkeVlXWmhhVzR3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREwKTXJTQ2hoQWhjWGJ5NnFQa0JNdFB6d0JJcVdzWFA1L2hKdVFrUGR1YWRJMTZtQ2o3ei9OTnVCcG5QbE40WmZoZgp4aGJhOGhjUjJLZUFYL044MkpMMWxLbkJYZ1JnSjFDVGVUSncxVFNkYk1FQTdWclk4VENHbUd6V2VpUzR0YThNCjMyYllwcmVSd2FBQmxMS1lJRVNNTnQ5UGQzN01KbDY2dlV0YjhpSStTQjNGZFBOODlpTW1Kb2dBa05aVFJLZ00KQkNOVk1sNFFsVTVqdzU4ZklLN2JiVy9tcHFxOW15ZFV0eS9mNW8wRVV0dmcvQ0dSV1NQN21sYS9FY2xRZFk3VwpWOFd6cGpwbXNBVlhxa1BsZEpRdVJkMksxV3lHMVhjU3lvajJxb2R4ZUZhSzA4RXR3MVIvWktVeHRKOUFYMDBPCjVpQzZzc0RoaTRHUXFoV1gxYVdiQWdNQkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUJCakFQQmdOVkhSTUIKQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUamd2UkxPR3lnL2EyL0paMmp6TWdSVkxZWFlqQU5CZ2txaGtpRwo5dzBCQVFzRkFBT0NBUUVBbVlIK0RHa2tjejZ2VGMwYndGSWllQWtmUmt3cHg3b1Y1dVhseUJlL1NKUk9BV1NJCkxlWXdIY05uZ3hpRlpCVXM0NnY5cGI5dXpHWTZzUzhSQk11emhwKzR6RXBuYitmemgzR01hdW1acnJGQTh6U1AKTWx3N0FSZ1B2VUhISnAwcWoyZXBJNFMyVmtmZzdORnVkaFZCdWF4RXFYMVFCRFNOZmZvU25oU2hSc3grMENFWAp3Qk9JbHQ2QmNJbTZaODhYdzdpbjNYYW1iNjAzaFhFY2tMUStrR0R4a282V0VvVytkc3V2ZFVnN3N0WDdSU3pQCjdHMmNqYVEyS1N4c2xXM2JZeW4wSVZ4WGF0MUVrWFNlM044MGJYbFJLV1luZldBZm00MHh1SzFGeDV2dVBCbkIKVDFtRDhGK01JSkRFVmdGNDJIZjAyQnJQVnIvbXl5OVlHdGRudmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  admissionReviewVersions:
    - v1beta1
  timeoutSeconds: 1