sudo: required

language: go

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

os:
  - linux

go:
  - 1.13
  - tip


env:
  global:
    - GO111MODULE="on"
    - BUILD_HASH=$(echo ${TRAVIS_COMMIT} | cut -c 1-10)
    - MAIN_GO_VERSION=1.13
    - GORACE="halt_on_error=1"
    - BUILD_VERSION=$(git describe --tags --abbrev=9 | sed 's/^v//')

script:
  - set -eo pipefail
  - make all;
  - if [[ "$TRAVIS_GO_VERSION" == "$MAIN_GO_VERSION" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    release_latest=$( [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_TAG" == "" && "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]] && echo "yes" || echo "no" );
    release_tag=$( [[ "$TRAVIS_TAG" != "" ]] && echo "yes" || echo "no" );

    if [[ $release_latest == "yes" ]]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag  "alpetest/grafain:${BUILD_HASH}" "alpetest/grafain:latest" ;
    docker push "alpetest/grafain:latest";
    docker tag  "alpetest/grafaincli:${BUILD_HASH}" "alpetest/grafaincli:latest" ;
    docker push "alpetest/grafaincli:latest";
    docker tag  "alpetest/grafainboard:${BUILD_HASH}" "alpetest/grafainboard:latest" ;
    docker push "alpetest/grafainboard:latest";
    docker logout;
    fi;

    if [[ $release_tag == "yes" ]]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag  "alpetest/grafain:${BUILD_HASH}" "alpetest/grafain:$TRAVIS_TAG" ;
    docker push "alpetest/grafain:$TRAVIS_TAG";
    docker tag  "alpetest/grafaincli:${BUILD_HASH}" "alpetest/grafaincli:$TRAVIS_TAG" ;
    docker push "alpetest/grafaincli:$TRAVIS_TAG";
    docker tag  "alpetest/grafainboard:${BUILD_HASH}" "alpetest/grafainboard:$TRAVIS_TAG" ;
    docker push "alpetest/grafainboard:$TRAVIS_TAG";
    docker logout;
    fi;
    fi;


notifications:
  email: false

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.x$/        # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/   # release tags

deploy:
  provider: releases
  api_key:
    ${GITHUB_API_KEY}
  file:
    - ${TRAVIS_BUILD_DIR}/cmd/grafaind/grafaind-${BUILD_VERSION}-linux-amd64.tar.gz
    - ${TRAVIS_BUILD_DIR}/cmd/grafaind/grafaind-${BUILD_VERSION}-linux-amd64.sha256
    - ${TRAVIS_BUILD_DIR}/cmd/grafaincli/grafaincli-${BUILD_VERSION}-linux-amd64.tar.gz
    - ${TRAVIS_BUILD_DIR}/cmd/grafaincli/grafaincli-${BUILD_VERSION}-linux-amd64.sha256
    - ${TRAVIS_BUILD_DIR}/cmd/grafaincli/grafainboard-${BUILD_VERSION}-linux-amd64.tar.gz
    - ${TRAVIS_BUILD_DIR}/cmd/grafaincli/grafainboard-${BUILD_VERSION}-linux-amd64.sha256
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
