# see https://github.com/golang/dep
[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.14.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.14.0"

[[override]]
  name = "github.com/go-kit/kit"
  version = "0.8.0"

[prune]
  go-tests = true
  unused-packages = true